Revert "support SearchParameters for IndexBinary (#4761)" (#70)
+ Firstly, the original commit
(https://github.com/facebookresearch/faiss/pull/4761) is not part of
v1.13.2.
+ We introduced this commit as part of
https://github.com/blevesearch/faiss/pull/68, hoping to ease out any
future merge conflicts on account of us adding searchParameters to
binary indexes.
+ But this causes a problem on mac platforms because of importing
`"omp.h"` into `faiss/impl/HNSW.h` and this in-turn being imported
within `c_api/IndexHNSW_c.cpp` ..

```
cd /Users/couchbase/workspace/cbdeps-platform-build/build/c_api && /usr/bin/c++ -Dfaiss_c_EXPORTS -I/Users/couchbase/workspace/cbdeps-platform-build/faiss -O2 -g -DNDEBUG -std=gnu++17 -arch arm64 -mmacosx-version-min=12.0 -fPIC -MD -MT c_api/CMakeFiles/faiss_c.dir/IndexLSH_c.cpp.o -MF CMakeFiles/faiss_c.dir/IndexLSH_c.cpp.o.d -o CMakeFiles/faiss_c.dir/IndexLSH_c.cpp.o -c /Users/couchbase/workspace/cbdeps-platform-build/faiss/c_api/IndexLSH_c.cpp
  In file included from /Users/couchbase/workspace/cbdeps-platform-build/faiss/c_api/IndexHNSW_c.cpp:11:
    /Users/couchbase/workspace/cbdeps-platform-build/faiss/faiss/impl/HNSW.h:13:10: fatal error: 'omp.h' file not found
```

This PR effectively reverts commit
c358a8ce5527822bcaeb6abefe9f52ed12fb6140.